// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   lb3314@EEWS304-017
//  Generated date: Thu May 14 21:14:54 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    render_blocks_core
// ------------------------------------------------------------------


module render_blocks_core (
  clk, en, arst_n, video_in_rsc_mgc_in_wire_d, blocks_rsc_mgc_in_wire_d, vga_xy_rsc_mgc_in_wire_d,
      video_out_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  input [79:0] blocks_rsc_mgc_in_wire_d;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;
  reg [29:0] video_out_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [29:0] io_read_video_in_rsc_d_cse_sva;
    reg [19:0] io_read_vga_xy_rsc_d_cse_sva;
    reg [79:0] FRAME_io_read_blocks_rsc_d_cse_sva;
    reg FRAME_1_slc_1_svs;
    reg FRAME_land_9_sva_1;
    reg FRAME_land_9_lpi_dfm;
    reg FRAME_land_6_sva_1;
    reg FRAME_land_6_lpi_dfm;
    reg FRAME_land_3_sva_1;
    reg FRAME_land_3_lpi_dfm;
    reg FRAME_2_slc_1_svs;
    reg FRAME_land_10_sva_1;
    reg FRAME_land_10_lpi_dfm;
    reg FRAME_land_7_sva_1;
    reg FRAME_land_7_lpi_dfm;
    reg FRAME_land_4_sva_1;
    reg FRAME_land_4_lpi_dfm;
    reg FRAME_3_slc_1_svs;
    reg FRAME_land_11_sva_1;
    reg FRAME_land_11_lpi_dfm;
    reg FRAME_land_8_sva_1;
    reg FRAME_land_8_lpi_dfm;
    reg FRAME_land_5_sva_1;
    reg FRAME_land_5_lpi_dfm;
    reg FRAME_4_slc_1_svs;
    reg FRAME_land_2_sva_1;
    reg FRAME_land_2_lpi_dfm;
    reg FRAME_land_1_sva_1;
    reg FRAME_land_1_lpi_dfm;
    reg FRAME_land_sva_1;
    reg FRAME_land_lpi_dfm;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        FRAME_land_sva_1 = 1'b0;
        FRAME_land_1_sva_1 = 1'b0;
        FRAME_land_2_sva_1 = 1'b0;
        FRAME_land_5_sva_1 = 1'b0;
        FRAME_land_8_sva_1 = 1'b0;
        FRAME_land_11_sva_1 = 1'b0;
        FRAME_land_4_sva_1 = 1'b0;
        FRAME_land_7_sva_1 = 1'b0;
        FRAME_land_10_sva_1 = 1'b0;
        FRAME_land_3_sva_1 = 1'b0;
        FRAME_land_6_sva_1 = 1'b0;
        FRAME_land_9_sva_1 = 1'b0;
        io_read_video_in_rsc_d_cse_sva = video_in_rsc_mgc_in_wire_d;
        io_read_vga_xy_rsc_d_cse_sva = vga_xy_rsc_mgc_in_wire_d;
        FRAME_io_read_blocks_rsc_d_cse_sva = blocks_rsc_mgc_in_wire_d;
        FRAME_1_slc_1_svs = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[9:0])
            , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[9:0])) ,
            1'b1})));
        if ( FRAME_1_slc_1_svs ) begin
          FRAME_land_9_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[9:0])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[9:0]))) + 12'b101111001111));
        end
        FRAME_land_9_lpi_dfm = FRAME_land_9_sva_1 & FRAME_1_slc_1_svs;
        if ( FRAME_land_9_lpi_dfm ) begin
          FRAME_land_6_sva_1 = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[19:10])
              , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[19:10]))
              , 1'b1})));
        end
        FRAME_land_6_lpi_dfm = FRAME_land_6_sva_1 & FRAME_land_9_lpi_dfm;
        if ( FRAME_land_6_lpi_dfm ) begin
          FRAME_land_3_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[19:10])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[19:10]))) +
              12'b101111001111));
        end
        FRAME_land_3_lpi_dfm = FRAME_land_3_sva_1 & FRAME_land_6_lpi_dfm;
        FRAME_2_slc_1_svs = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[29:20])
            , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[9:0])) ,
            1'b1})));
        if ( FRAME_2_slc_1_svs ) begin
          FRAME_land_10_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[9:0])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[29:20]))) +
              12'b101111001111));
        end
        FRAME_land_10_lpi_dfm = FRAME_land_10_sva_1 & FRAME_2_slc_1_svs;
        if ( FRAME_land_10_lpi_dfm ) begin
          FRAME_land_7_sva_1 = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[39:30])
              , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[19:10]))
              , 1'b1})));
        end
        FRAME_land_7_lpi_dfm = FRAME_land_7_sva_1 & FRAME_land_10_lpi_dfm;
        if ( FRAME_land_7_lpi_dfm ) begin
          FRAME_land_4_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[19:10])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[39:30]))) +
              12'b101111001111));
        end
        FRAME_land_4_lpi_dfm = FRAME_land_4_sva_1 & FRAME_land_7_lpi_dfm;
        FRAME_3_slc_1_svs = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[49:40])
            , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[9:0])) ,
            1'b1})));
        if ( FRAME_3_slc_1_svs ) begin
          FRAME_land_11_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[9:0])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[49:40]))) +
              12'b101111001111));
        end
        FRAME_land_11_lpi_dfm = FRAME_land_11_sva_1 & FRAME_3_slc_1_svs;
        if ( FRAME_land_11_lpi_dfm ) begin
          FRAME_land_8_sva_1 = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[59:50])
              , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[19:10]))
              , 1'b1})));
        end
        FRAME_land_8_lpi_dfm = FRAME_land_8_sva_1 & FRAME_land_11_lpi_dfm;
        if ( FRAME_land_8_lpi_dfm ) begin
          FRAME_land_5_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[19:10])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[59:50]))) +
              12'b101111001111));
        end
        FRAME_land_5_lpi_dfm = FRAME_land_5_sva_1 & FRAME_land_8_lpi_dfm;
        FRAME_4_slc_1_svs = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[69:60])
            , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[9:0])) ,
            1'b1})));
        if ( FRAME_4_slc_1_svs ) begin
          FRAME_land_2_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[9:0])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[69:60]))) +
              12'b101111001111));
        end
        FRAME_land_2_lpi_dfm = FRAME_land_2_sva_1 & FRAME_4_slc_1_svs;
        if ( FRAME_land_2_lpi_dfm ) begin
          FRAME_land_1_sva_1 = readslicef_12_1_11((({1'b1 , (FRAME_io_read_blocks_rsc_d_cse_sva[79:70])
              , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[19:10]))
              , 1'b1})));
        end
        FRAME_land_1_lpi_dfm = FRAME_land_1_sva_1 & FRAME_land_2_lpi_dfm;
        if ( FRAME_land_1_lpi_dfm ) begin
          FRAME_land_sva_1 = readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(io_read_vga_xy_rsc_d_cse_sva[19:10])
              + conv_u2u_10_11(~ (FRAME_io_read_blocks_rsc_d_cse_sva[79:70]))) +
              12'b101111001111));
        end
        FRAME_land_lpi_dfm = FRAME_land_sva_1 & FRAME_land_1_lpi_dfm;
        video_out_rsc_mgc_out_stdreg_d <= {((io_read_video_in_rsc_d_cse_sva[29:20])
            | ({{9{FRAME_land_3_lpi_dfm}}, FRAME_land_3_lpi_dfm}) | ({{9{FRAME_land_4_lpi_dfm}},
            FRAME_land_4_lpi_dfm}) | ({{9{FRAME_land_5_lpi_dfm}}, FRAME_land_5_lpi_dfm})
            | ({{9{FRAME_land_lpi_dfm}}, FRAME_land_lpi_dfm})) , (io_read_video_in_rsc_d_cse_sva[19:10])
            , ((io_read_video_in_rsc_d_cse_sva[9:0]) | ({{9{FRAME_land_3_lpi_dfm}},
            FRAME_land_3_lpi_dfm}) | ({{9{FRAME_land_4_lpi_dfm}}, FRAME_land_4_lpi_dfm})
            | ({{9{FRAME_land_5_lpi_dfm}}, FRAME_land_5_lpi_dfm}) | ({{9{FRAME_land_lpi_dfm}},
            FRAME_land_lpi_dfm}))};
      end
    end
    FRAME_land_lpi_dfm = 1'b0;
    FRAME_land_sva_1 = 1'b0;
    FRAME_land_1_lpi_dfm = 1'b0;
    FRAME_land_1_sva_1 = 1'b0;
    FRAME_land_2_lpi_dfm = 1'b0;
    FRAME_land_2_sva_1 = 1'b0;
    FRAME_4_slc_1_svs = 1'b0;
    FRAME_land_5_lpi_dfm = 1'b0;
    FRAME_land_5_sva_1 = 1'b0;
    FRAME_land_8_lpi_dfm = 1'b0;
    FRAME_land_8_sva_1 = 1'b0;
    FRAME_land_11_lpi_dfm = 1'b0;
    FRAME_land_11_sva_1 = 1'b0;
    FRAME_3_slc_1_svs = 1'b0;
    FRAME_land_4_lpi_dfm = 1'b0;
    FRAME_land_4_sva_1 = 1'b0;
    FRAME_land_7_lpi_dfm = 1'b0;
    FRAME_land_7_sva_1 = 1'b0;
    FRAME_land_10_lpi_dfm = 1'b0;
    FRAME_land_10_sva_1 = 1'b0;
    FRAME_2_slc_1_svs = 1'b0;
    FRAME_land_3_lpi_dfm = 1'b0;
    FRAME_land_3_sva_1 = 1'b0;
    FRAME_land_6_lpi_dfm = 1'b0;
    FRAME_land_6_sva_1 = 1'b0;
    FRAME_land_9_lpi_dfm = 1'b0;
    FRAME_land_9_sva_1 = 1'b0;
    FRAME_1_slc_1_svs = 1'b0;
    FRAME_io_read_blocks_rsc_d_cse_sva = 80'b0;
    io_read_vga_xy_rsc_d_cse_sva = 20'b0;
    io_read_video_in_rsc_d_cse_sva = 30'b0;
    video_out_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_12_1_11;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 11;
    readslicef_12_1_11 = tmp[0:0];
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    render_blocks
//  Generated from file(s):
//    9) $PROJECT_HOME/block_render.c
// ------------------------------------------------------------------


module render_blocks (
  video_in_rsc_z, blocks_rsc_z, vga_xy_rsc_z, video_out_rsc_z, clk, en, arst_n
);
  input [29:0] video_in_rsc_z;
  input [79:0] blocks_rsc_z;
  input [19:0] vga_xy_rsc_z;
  output [29:0] video_out_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [79:0] blocks_rsc_mgc_in_wire_d;
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(80)) blocks_rsc_mgc_in_wire (
      .d(blocks_rsc_mgc_in_wire_d),
      .z(blocks_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  render_blocks_core render_blocks_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .blocks_rsc_mgc_in_wire_d(blocks_rsc_mgc_in_wire_d),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d)
    );
endmodule



