// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   lb3314@EEWS304-017
//  Generated date: Thu May 14 21:15:02 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    render_blocks_core
// ------------------------------------------------------------------


module render_blocks_core (
  clk, en, arst_n, video_in_rsc_mgc_in_wire_d, blocks_rsc_mgc_in_wire_d, vga_xy_rsc_mgc_in_wire_d,
      video_out_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  input [79:0] blocks_rsc_mgc_in_wire_d;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  reg [9:0] reg_video_out_rsc_mgc_out_stdreg_d_tmp;
  reg [9:0] reg_video_out_rsc_mgc_out_stdreg_d_tmp_1;
  reg [9:0] reg_video_out_rsc_mgc_out_stdreg_d_tmp_2;
  wire FRAME_if_and_2_itm;
  wire FRAME_if_and_5_itm;
  wire FRAME_if_and_8_itm;
  wire FRAME_if_and_11_itm;


  // Interconnect Declarations for Component Instantiations 
  assign video_out_rsc_mgc_out_stdreg_d = {reg_video_out_rsc_mgc_out_stdreg_d_tmp
      , reg_video_out_rsc_mgc_out_stdreg_d_tmp_1 , reg_video_out_rsc_mgc_out_stdreg_d_tmp_2};
  assign FRAME_if_and_2_itm = (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[19:10])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[19:10]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[19:10]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[19:10])) , 1'b1})))) & (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[9:0])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[9:0]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[9:0]) , 1'b1}) +
      conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[9:0])) , 1'b1}))));
  assign FRAME_if_and_5_itm = (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[19:10])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[39:30]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[39:30]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[19:10])) , 1'b1})))) & (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[9:0])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[29:20]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[29:20]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[9:0])) , 1'b1}))));
  assign FRAME_if_and_8_itm = (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[19:10])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[59:50]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[59:50]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[19:10])) , 1'b1})))) & (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[9:0])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[49:40]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[49:40]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[9:0])) , 1'b1}))));
  assign FRAME_if_and_11_itm = (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[19:10])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[79:70]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[79:70]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[19:10])) , 1'b1})))) & (readslicef_12_1_11((conv_u2s_11_12(conv_u2u_10_11(vga_xy_rsc_mgc_in_wire_d[9:0])
      + conv_u2u_10_11(~ (blocks_rsc_mgc_in_wire_d[69:60]))) + 12'b101111001111)))
      & (readslicef_12_1_11((({1'b1 , (blocks_rsc_mgc_in_wire_d[69:60]) , 1'b1})
      + conv_u2u_11_12({(~ (vga_xy_rsc_mgc_in_wire_d[9:0])) , 1'b1}))));
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      reg_video_out_rsc_mgc_out_stdreg_d_tmp <= 10'b0;
      reg_video_out_rsc_mgc_out_stdreg_d_tmp_1 <= 10'b0;
      reg_video_out_rsc_mgc_out_stdreg_d_tmp_2 <= 10'b0;
    end
    else begin
      if ( en ) begin
        reg_video_out_rsc_mgc_out_stdreg_d_tmp <= (video_in_rsc_mgc_in_wire_d[29:20])
            | ({{9{FRAME_if_and_2_itm}}, FRAME_if_and_2_itm}) | ({{9{FRAME_if_and_5_itm}},
            FRAME_if_and_5_itm}) | ({{9{FRAME_if_and_8_itm}}, FRAME_if_and_8_itm})
            | ({{9{FRAME_if_and_11_itm}}, FRAME_if_and_11_itm});
        reg_video_out_rsc_mgc_out_stdreg_d_tmp_1 <= video_in_rsc_mgc_in_wire_d[19:10];
        reg_video_out_rsc_mgc_out_stdreg_d_tmp_2 <= (video_in_rsc_mgc_in_wire_d[9:0])
            | ({{9{FRAME_if_and_2_itm}}, FRAME_if_and_2_itm}) | ({{9{FRAME_if_and_5_itm}},
            FRAME_if_and_5_itm}) | ({{9{FRAME_if_and_8_itm}}, FRAME_if_and_8_itm})
            | ({{9{FRAME_if_and_11_itm}}, FRAME_if_and_11_itm});
      end
    end
  end

  function [0:0] readslicef_12_1_11;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 11;
    readslicef_12_1_11 = tmp[0:0];
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    render_blocks
//  Generated from file(s):
//    9) $PROJECT_HOME/block_render.c
// ------------------------------------------------------------------


module render_blocks (
  video_in_rsc_z, blocks_rsc_z, vga_xy_rsc_z, video_out_rsc_z, clk, en, arst_n
);
  input [29:0] video_in_rsc_z;
  input [79:0] blocks_rsc_z;
  input [19:0] vga_xy_rsc_z;
  output [29:0] video_out_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [79:0] blocks_rsc_mgc_in_wire_d;
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(80)) blocks_rsc_mgc_in_wire (
      .d(blocks_rsc_mgc_in_wire_d),
      .z(blocks_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  render_blocks_core render_blocks_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .blocks_rsc_mgc_in_wire_d(blocks_rsc_mgc_in_wire_d),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d)
    );
endmodule



