// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   lb3314@EEWS304-017
//  Generated date: Thu May 14 19:23:40 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    is_pixel_match_core
// ------------------------------------------------------------------


module is_pixel_match_core (
  clk, en, arst_n, video_in_rsc_mgc_in_wire_d, video_out_rsc_mgc_out_stdreg_d, box_xy_rsc_mgc_in_wire_d,
      vga_xy_rsc_mgc_in_wire_d, o_x_rsc_mgc_out_stdreg_d, counter_rsc_mgc_out_stdreg_d,
      do_calc_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;
  reg [29:0] video_out_rsc_mgc_out_stdreg_d;
  input [19:0] box_xy_rsc_mgc_in_wire_d;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  output [7:0] o_x_rsc_mgc_out_stdreg_d;
  reg [7:0] o_x_rsc_mgc_out_stdreg_d;
  output [1:0] counter_rsc_mgc_out_stdreg_d;
  reg [1:0] counter_rsc_mgc_out_stdreg_d;
  output [1:0] do_calc_rsc_mgc_out_stdreg_d;
  reg [1:0] do_calc_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [29:0] io_read_video_in_rsc_d_cse_sva;
    reg [19:0] io_read_box_xy_rsc_d_cse_sva;
    reg [7:0] box_r_sg1_sva;
    reg [8:0] box_b_sg1_sva;
    reg [19:0] io_read_vga_xy_rsc_d_cse_sva;
    reg [9:0] luma_lpi_dfm;
    reg slc_2_svs;
    reg land_2_sva_1;
    reg land_2_lpi_dfm;
    reg land_1_sva_1;
    reg land_1_lpi_dfm;
    reg land_sva_1;
    reg land_lpi_dfm;
    reg if_2_slc_mdf_sva;
    reg [7:0] if_2_if_acc_dfmergedata_sva;
    reg [7:0] if_2_if_acc_dfmergedata_lpi_dfm;
    reg equal_svs;
    reg land_3_sva_1;

    reg[9:0] mux_1_nl;
    reg[9:0] mux_2_nl;
    reg[9:0] mux_3_nl;
    reg[9:0] mux_4_nl;
    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        land_3_sva_1 = 1'b0;
        if_2_if_acc_dfmergedata_lpi_dfm = 8'b0;
        if_2_if_acc_dfmergedata_sva = 8'b0;
        if_2_slc_mdf_sva = 1'b0;
        land_sva_1 = 1'b0;
        land_1_sva_1 = 1'b0;
        land_2_sva_1 = 1'b0;
        io_read_video_in_rsc_d_cse_sva = video_in_rsc_mgc_in_wire_d;
        io_read_box_xy_rsc_d_cse_sva = box_xy_rsc_mgc_in_wire_d;
        box_r_sg1_sva = (io_read_box_xy_rsc_d_cse_sva[9:2]) + 8'b11001;
        box_b_sg1_sva = (~ (io_read_box_xy_rsc_d_cse_sva[19:11])) + 9'b11001;
        io_read_vga_xy_rsc_d_cse_sva = vga_xy_rsc_mgc_in_wire_d;
        slc_2_svs = readslicef_12_1_11((({1'b1 , (io_read_box_xy_rsc_d_cse_sva[9:0])
            , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[9:0])) ,
            1'b1})));
        if ( slc_2_svs ) begin
          land_2_sva_1 = readslicef_12_1_11((({1'b1 , (io_read_vga_xy_rsc_d_cse_sva[9:0])
              , 1'b1}) + conv_u2u_11_12({(~ box_r_sg1_sva) , (~ (io_read_box_xy_rsc_d_cse_sva[1:0]))
              , 1'b1})));
        end
        land_2_lpi_dfm = land_2_sva_1 & slc_2_svs;
        if ( land_2_lpi_dfm ) begin
          land_1_sva_1 = readslicef_12_1_11((({1'b1 , (~ (io_read_box_xy_rsc_d_cse_sva[19:10]))
              , 1'b1}) + conv_u2u_11_12({(~ (io_read_vga_xy_rsc_d_cse_sva[19:10]))
              , 1'b1})));
        end
        land_1_lpi_dfm = land_1_sva_1 & land_2_lpi_dfm;
        if ( land_1_lpi_dfm ) begin
          land_sva_1 = readslicef_12_1_11((({1'b1 , (io_read_vga_xy_rsc_d_cse_sva[19:10])
              , 1'b1}) + conv_u2u_11_12({(~ box_b_sg1_sva) , (io_read_box_xy_rsc_d_cse_sva[10])
              , 1'b1})));
        end
        land_lpi_dfm = land_sva_1 & land_1_lpi_dfm;
        if ( land_lpi_dfm ) begin
          luma_lpi_dfm = MUX_v_10_2_2({(io_read_video_in_rsc_d_cse_sva[29:20]) ,
              (io_read_video_in_rsc_d_cse_sva[19:10])}, readslicef_12_1_11((({1'b1
              , (io_read_video_in_rsc_d_cse_sva[29:20]) , 1'b1}) + conv_u2u_11_12({(~
              (io_read_video_in_rsc_d_cse_sva[19:10])) , 1'b1}))));
          mux_1_nl = MUX_v_10_2_2({luma_lpi_dfm , (io_read_video_in_rsc_d_cse_sva[9:0])},
              readslicef_12_1_11((({1'b1 , luma_lpi_dfm , 1'b1}) + conv_u2u_11_12({(~
              (io_read_video_in_rsc_d_cse_sva[9:0])) , 1'b1}))));
          if_2_slc_mdf_sva = readslicef_11_1_10((({1'b1 , (~ (mux_1_nl))}) + 11'b1100101));
          if ( if_2_slc_mdf_sva ) begin
          end
          else begin
            if_2_if_acc_dfmergedata_sva = readslicef_9_8_1((({(io_read_vga_xy_rsc_d_cse_sva[7:0])
                , 1'b1}) + ({(~ (io_read_box_xy_rsc_d_cse_sva[7:0])) , 1'b1})));
          end
          if_2_if_acc_dfmergedata_lpi_dfm = if_2_if_acc_dfmergedata_sva & (signext_8_1(~
              if_2_slc_mdf_sva));
        end
        counter_rsc_mgc_out_stdreg_d <= {1'b0, ~(if_2_slc_mdf_sva | (~ land_lpi_dfm))};
        o_x_rsc_mgc_out_stdreg_d <= if_2_if_acc_dfmergedata_lpi_dfm & ({{7{land_lpi_dfm}},
            land_lpi_dfm});
        equal_svs = (io_read_vga_xy_rsc_d_cse_sva[9:0]) == ({box_r_sg1_sva , (io_read_box_xy_rsc_d_cse_sva[1:0])});
        if ( equal_svs ) begin
          land_3_sva_1 = (io_read_vga_xy_rsc_d_cse_sva[19:10]) == ({box_b_sg1_sva
              , (~ (io_read_box_xy_rsc_d_cse_sva[10]))});
        end
        do_calc_rsc_mgc_out_stdreg_d <= {1'b0, land_3_sva_1 & equal_svs};
        mux_2_nl = MUX_v_10_2_2({(io_read_video_in_rsc_d_cse_sva[29:20]) , (signext_10_1(~
            if_2_slc_mdf_sva))}, land_lpi_dfm);
        mux_3_nl = MUX_v_10_2_2({(io_read_video_in_rsc_d_cse_sva[19:10]) , (signext_10_1(~
            if_2_slc_mdf_sva))}, land_lpi_dfm);
        mux_4_nl = MUX_v_10_2_2({(io_read_video_in_rsc_d_cse_sva[9:0]) , (signext_10_1(~
            if_2_slc_mdf_sva))}, land_lpi_dfm);
        video_out_rsc_mgc_out_stdreg_d <= {(mux_2_nl) , (mux_3_nl) , (mux_4_nl)};
      end
    end
    land_3_sva_1 = 1'b0;
    equal_svs = 1'b0;
    if_2_if_acc_dfmergedata_lpi_dfm = 8'b0;
    if_2_if_acc_dfmergedata_sva = 8'b0;
    if_2_slc_mdf_sva = 1'b0;
    land_lpi_dfm = 1'b0;
    land_sva_1 = 1'b0;
    land_1_lpi_dfm = 1'b0;
    land_1_sva_1 = 1'b0;
    land_2_lpi_dfm = 1'b0;
    land_2_sva_1 = 1'b0;
    slc_2_svs = 1'b0;
    luma_lpi_dfm = 10'b0;
    io_read_vga_xy_rsc_d_cse_sva = 20'b0;
    box_b_sg1_sva = 9'b0;
    box_r_sg1_sva = 8'b0;
    io_read_box_xy_rsc_d_cse_sva = 20'b0;
    io_read_video_in_rsc_d_cse_sva = 30'b0;
    do_calc_rsc_mgc_out_stdreg_d <= 2'b0;
    counter_rsc_mgc_out_stdreg_d <= 2'b0;
    o_x_rsc_mgc_out_stdreg_d <= 8'b0;
    video_out_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_12_1_11;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 11;
    readslicef_12_1_11 = tmp[0:0];
  end
  endfunction


  function [9:0] MUX_v_10_2_2;
    input [19:0] inputs;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[19:10];
      end
      1'b1 : begin
        result = inputs[9:0];
      end
      default : begin
        result = inputs[19:10];
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [7:0] readslicef_9_8_1;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_9_8_1 = tmp[7:0];
  end
  endfunction


  function [7:0] signext_8_1;
    input [0:0] vector;
  begin
    signext_8_1= {{7{vector[0]}}, vector};
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    is_pixel_match
//  Generated from file(s):
//   10) $PROJECT_HOME/color_summer.c
// ------------------------------------------------------------------


module is_pixel_match (
  video_in_rsc_z, video_out_rsc_z, box_xy_rsc_z, vga_xy_rsc_z, o_x_rsc_z, counter_rsc_z,
      do_calc_rsc_z, clk, en, arst_n
);
  input [29:0] video_in_rsc_z;
  output [29:0] video_out_rsc_z;
  input [19:0] box_xy_rsc_z;
  input [19:0] vga_xy_rsc_z;
  output [7:0] o_x_rsc_z;
  output [1:0] counter_rsc_z;
  output [1:0] do_calc_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;
  wire [19:0] box_xy_rsc_mgc_in_wire_d;
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [7:0] o_x_rsc_mgc_out_stdreg_d;
  wire [1:0] counter_rsc_mgc_out_stdreg_d;
  wire [1:0] do_calc_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(20)) box_xy_rsc_mgc_in_wire (
      .d(box_xy_rsc_mgc_in_wire_d),
      .z(box_xy_rsc_z)
    );
  mgc_in_wire #(.rscid(4),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_out_stdreg #(.rscid(5),
  .width(8)) o_x_rsc_mgc_out_stdreg (
      .d(o_x_rsc_mgc_out_stdreg_d),
      .z(o_x_rsc_z)
    );
  mgc_out_stdreg #(.rscid(6),
  .width(2)) counter_rsc_mgc_out_stdreg (
      .d(counter_rsc_mgc_out_stdreg_d),
      .z(counter_rsc_z)
    );
  mgc_out_stdreg #(.rscid(7),
  .width(2)) do_calc_rsc_mgc_out_stdreg (
      .d(do_calc_rsc_mgc_out_stdreg_d),
      .z(do_calc_rsc_z)
    );
  is_pixel_match_core is_pixel_match_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d),
      .box_xy_rsc_mgc_in_wire_d(box_xy_rsc_mgc_in_wire_d),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .o_x_rsc_mgc_out_stdreg_d(o_x_rsc_mgc_out_stdreg_d),
      .counter_rsc_mgc_out_stdreg_d(counter_rsc_mgc_out_stdreg_d),
      .do_calc_rsc_mgc_out_stdreg_d(do_calc_rsc_mgc_out_stdreg_d)
    );
endmodule



